[build]
  command = "npm run build"
  publish = "dist"

# 配置大文件处理和缓存
[[headers]]
  for = "/*.data"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/octet-stream"
    Content-Encoding = "identity"
    Access-Control-Allow-Origin = "*"

# 增加请求超时时间
[functions]
  timeout = 900

# 配置CDN行为
[cdn]
  enabled = true
  compression = "manual"

# 配置重定向以确保正确的资源路径
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200